post_format: ["BTS storytelling","CapCut montage","Talking-head tip","Static carousel","Single image","Short/vertical","Live","Community post","Pin"]
caption_style: ["Short hook","Story paragraph","Recipe/How-to notes","Question/Poll","CTA/promo","Announcement"]
hashtag_type: ["General","Niche","Branded","Mixed"]
content_category: ["Recipe","Behind-the-scenes","Tutorial","Product","Lifestyle","Announcement","UGC"]
campaign: ["BTS","Storytelling","Growth","Launch","Promo","Evergreen"]
